#!/bin/bash
# Enforce this project's spec-kit extension policy.
#
# spec-kit 0.16.x ships extensions that `specify init --here --force` enables by
# default. One of them, `git`, registers five skills — speckit-git-feature,
# -git-validate, -git-commit, -git-remote, -git-initialize — that directly
# contradict how these projects work:
#
#   - git-feature creates numbered FEATURE BRANCHES, but .claude/rules/spec-register.md
#     is explicit: "No feature branches, no merge step" — one spec, one commit,
#     pushed straight to the working branch;
#   - git-validate enforces feature-branch NAMING, which only makes sense given
#     the branches we do not create;
#   - git-commit auto-commits after every Spec Kit phase, which would shred the
#     one-commit-per-spec protocol and bypass the commit-message discipline.
#
# Nothing auto-fires today — branch creation is not wired into create-new-feature.sh
# — but the skills are model-invocable, so a future session can reach for them
# believing they are part of the pipeline. Prose in a rule file does not stop that;
# disabling the extension does.
#
# `agent-context` stays ENABLED: refreshing the managed Spec Kit section of the
# agent context file is useful and conflicts with nothing.
#
# Idempotent, silent when the policy already holds. Must run AFTER every
# `specify init --force`, which re-enables everything.
#
# Usage: speckit-extension-policy.sh [--repo <path>] [--dry-run]
# Exit: 0 = policy holds (changed or already correct), 1 = could not apply.

set -u

REPO=""; DRY=0
while [ $# -gt 0 ]; do
  case "$1" in
    --repo)    shift; REPO="${1:-}" ;;
    --dry-run) DRY=1 ;;
    -h|--help) grep -E '^#( |$)' "$0" | sed -e 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "unknown flag: $1" >&2; exit 1 ;;
  esac
  shift
done

[ -n "$REPO" ] || REPO=$(git rev-parse --show-toplevel 2>/dev/null || echo "$PWD")
# ------------------------------------------------- pipeline stops (spec-kit 1.0+)
# spec-kit 1.0 moved two "wait for the user" prompts INTO its own skills:
#
#   speckit-implement — counts unchecked checklist items and, when any are
#     unchecked, instructs: **STOP** and ask "Some checklists have unchecked
#     items. Do you want to proceed with implementation anyway? (yes/no)" —
#     "Wait for user response before continuing".
#   speckit-specify   — renders a clarification table ending in
#     "**Your choice**: _[Wait for user response]_".
#
# Both are permission-checks on work the developer already authorized, which
# .claude/rules/continuous-execution.md forbids outright, and the second
# duplicates a decision this project already auto-picks. Prose in a rule file is
# the durable override, but the skills are regenerated by every
# `specify init --force`, and a model reading "STOP and ask" in the skill it is
# executing is being told twice by the thing closest to it. So rewrite them.
#
# Runs BEFORE the registry check below on purpose: a 1.0 project has no
# .specify/extensions/.registry at all, and that early exit is exactly where
# these stops live.
#
# Surgical and idempotent: each patch fires only on the verbatim upstream text
# and stamps a marker, so a re-run is a no-op and a spec-kit that changes the
# wording is left alone (loudly) rather than half-edited.
neutralize_stops() {
  _root="$1"
  command -v python3 >/dev/null 2>&1 || return 0
  DRY="$DRY" python3 - "$_root" <<'PYEOF'
import os, sys, pathlib

root = pathlib.Path(sys.argv[1])
dry = os.environ.get("DRY") == "1"
MARK = "<!-- speckit-nostop: patched by scripts/speckit-extension-policy.sh -->"

IMPL_OLD = """     - **STOP** and ask: "Some checklists have unchecked items. Do you want to proceed with implementation anyway? (yes/no)"
     - Wait for user response before continuing
     - If user says "no" or "wait" or "stop", halt execution
     - If user says "yes" or "proceed" or "continue", proceed to step 3
"""
IMPL_NEW = """     - Do NOT stop and do NOT ask. This project runs the pipeline as ONE uninterrupted
       task (.claude/rules/continuous-execution.md); a permission-check here is on work
       the developer already authorized. Instead: read the unchecked items, tick the ones
       already satisfied, and record any that name a real gap (a missing acceptance
       criterion, an unanswered authorization question, an absent error state) in the spec
       and in <spec-dir>/run-log.md. Then proceed to step 3. What was left unchecked is
       reported in the per-spec status summary, which is the one stop this pipeline has.
"""

SPEC_OLD = "           **Your choice**: _[Wait for user response]_"
SPEC_NEW = ("           **Your choice**: _[Do not wait. Auto-select the recommended option and record it —\n"
            "           this project auto-picks clarification answers (.claude/rules/feature-pipeline.md).]_")

targets = [
    (root / ".claude/skills/speckit-implement/SKILL.md", IMPL_OLD, IMPL_NEW, "implement checklist stop"),
    (root / ".claude/skills/speckit-specify/SKILL.md",   SPEC_OLD, SPEC_NEW, "specify clarification wait"),
]

done, absent = [], []
for path, old, new, label in targets:
    if not path.exists():
        continue
    text = path.read_text(encoding="utf-8")
    if MARK in text:
        continue                      # already patched
    if old not in text:
        absent.append(label)          # upstream wording moved
        continue
    if dry:
        done.append(label + " (would patch)")
        continue
    path.write_text(text.replace(old, new, 1) + "\n" + MARK + "\n", encoding="utf-8")
    done.append(label)

for label in done:
    print(f"speckit-extension-policy: neutralized {label}")
for label in absent:
    print(f"speckit-extension-policy: WARNING — could not find the {label}; spec-kit changed its wording. "
          f"The rule in .claude/rules/feature-pipeline.md still governs: never relay that prompt.", file=sys.stderr)
PYEOF
  return 0
}
neutralize_stops "$REPO"

REG="$REPO/.specify/extensions/.registry"
[ -f "$REG" ] || exit 0            # no spec-kit extensions here — nothing to enforce
command -v python3 >/dev/null 2>&1 || exit 0

# Extensions this project refuses to run. Space-separated.
DISABLE="${SPECKIT_DISABLED_EXTENSIONS:-git}"

# Flipping the registry flag is only half the job. `enabled: false` governs what
# SPEC-KIT wires; it does not delete the skill files, and Claude Code discovers
# skills by file presence. The five speckit-git-* SKILL.md files ship with
# `disable-model-invocation: false`, so Claude can still reach for
# /speckit-git-feature on a disabled extension. Flip that frontmatter too:
# `user-invocable: true` is left alone, so a human can still run one
# deliberately — the model just cannot pick it up on its own.
neutralize_skills() {
  _root="$1"; _n=0
  for _sk in "$_root"/.claude/skills/speckit-git-*/SKILL.md; do
    [ -f "$_sk" ] || continue
    grep -q '^disable-model-invocation: false' "$_sk" 2>/dev/null || continue
    [ "$DRY" = "1" ] && { _n=$((_n + 1)); continue; }
    _tmp="$_sk.tmp.$$"
    sed 's/^disable-model-invocation: false/disable-model-invocation: true/' "$_sk" > "$_tmp" 2>/dev/null \
      && mv "$_tmp" "$_sk" && _n=$((_n + 1))
    rm -f "$_tmp" 2>/dev/null
  done
  [ "$_n" -gt 0 ] && printf 'speckit-extension-policy: %s disable-model-invocation on %s speckit-git-* skill(s)\n' \
    "$([ "$DRY" = "1" ] && echo 'would set' || echo 'set')" "$_n"
  return 0
}
neutralize_skills "$REPO"

python3 - "$REG" "$DISABLE" "$DRY" <<'PY'
import json, sys
path, disable, dry = sys.argv[1], sys.argv[2].split(), sys.argv[3] == "1"
try:
    with open(path) as fh:
        data = json.load(fh)
except Exception as exc:
    print(f"speckit-extension-policy: cannot read registry ({exc})", file=sys.stderr)
    sys.exit(1)

exts = data.get("extensions", {})
changed = []
for name in disable:
    ext = exts.get(name)
    if isinstance(ext, dict) and ext.get("enabled") is not False:
        ext["enabled"] = False
        changed.append(name)

if not changed:
    sys.exit(0)

if not dry:
    with open(path, "w") as fh:
        json.dump(data, fh, indent=2)
        fh.write("\n")

skills = []
for name in changed:
    skills += exts[name].get("registered_skills", [])
print(f"speckit-extension-policy: {'would disable' if dry else 'disabled'} "
      f"{', '.join(changed)} ({len(skills)} skill(s): {', '.join(skills)})")
print("  reason: feature branches / per-phase auto-commit conflict with "
      ".claude/rules/spec-register.md (one spec, one commit, direct push)")
PY
